FROM apache/airflow:2.2.2
RUN pip install --upgrade pip
RUN pip install --no-cache-dir \
    requests==2.26.0 \
    pandas==1.1.5 \
    pandas-gbq==0.16.0 \
    geopandas==0.10.2 \
    google-cloud-storage==1.42.3 \
    SQLAlchemy==1.3.20 \
    python-dotenv==0.19.1 \
    google-cloud-bigquery-storage==2.9.1
